openapi: 3.0.0
info:
  title: JC Envíos API
  version: 1.0.0
paths:
  /api/?accion=loginUser:
    post:
      summary: Iniciar sesión
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email: {type: string}
                password: {type: string}
  /api/?accion=createTransaccion:
    post:
      summary: Crear nueva remesa
      security:
        - sessionAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [montoOrigen, cuentaID]
              properties:
                montoOrigen: {type: number}
                cuentaID: {type: integer}